### ISSUE TITLE
Update documentation with wrapper plugin (was: Pluginifiy and rename default mode)

### ISSUE THREAD

**Issue by n-osborne** [ocaml-gospel/ortac#100]
This will allow to release only the `qcheck-stm` plugin and the `ortac-core` translation.

Idea for renaming default mode is `wrapper`
We can also rename the `ortac ` parckage into `ortac-core`

Update READMEs accordingly

**Comment by shym** [comment]
I reopen this issue, just to keep track of the fact that the READMEs still need to be updated.
