### ISSUE TITLE
[qcheck-stm] Running tests causing segmentation faults

### ISSUE THREAD

**Issue by nikolaushuber** [ocaml-gospel/ortac#254]
When running a test with qcheck-stm that causes a segmentation fault there is not output to the user about which series of function calls lead to this scenario. 

Currently the only option is to manually adapt the call to `Test.make` in `/plugins/qcheck-stm/src/runtime/ortac_runtime_qcheck_stm.ml` to use `Util.fork_prop_with_timeout`. Maybe there could be a commandline flag to use this automatically, so that this manual adaptation is not needed?

**Comment by n-osborne** [comment]
I completely agree, we should have the possibility of using this nice QCheck-STM feature!

The command-line flag seems like a good option, as most of the time users simply don't have to speficy it.
We could also add an optional value to the config file like:

```ocaml
let may_segfault = true
```

Letting Ortac/QCheck-STM  interpret the lack of such value as a negative. This has the benefit of consistency: all configuration goes in the configuration file.

Note that we need to adapt the dune plugin too to include such feature in a release in case of the first solution (the second is transparent for the dune plugin).

**Comment by nikolaushuber** [comment]
There is an interesting question here, whether the command-line flag should be for `ortac` or for the generated test executable. The particular difference in running tests in a separate process is part of the `Ortac_runtime_qcheck_stm` module, therefore there is not necessarily any change in the generated code. 

We could of course make it an additional input to `agree_test` as well. 

A quite simple solution could be to look for the presence of an environment variable inside `Ortac_runtime_qcheck_stm.agree_test`, so that one could first run the generated test as is, and in case of a segmentation fault set an environment variable to run the tests in separate processes in order to get more feedback. 

This is also just a bit loud thinking from my part 😄.

**Comment by n-osborne** [comment]
You're right, there is indeed no need to modify the generated code as the QCheck proposition is build in the runtime.
The environment variable is beginning to sound appealing as it implies only minimal intervention in the runtime.
When running tests in the CI, this can be set by the `setenv` dune stanza.
The dune plugin should still be updated in this case to handle that too (which is ok).
