### ISSUE TITLE
[qcheck-stm] Unable to test a pure interface: "functions returning a SUT value cannot be tested"

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml-gospel/ortac#256]
I was hoping to use QCheck-STM to test a pure Int31 interface because, although it is designed to test mutable interfaces, it seems to be the only working option for API testing at the moment.

What I tried to do was to test an API with a dummy `Int31.t` as an initial SUT:

```ocaml
type t
(*@ model i : integer *)

val of_int : int -> t
(*@ x = of_int j
    ensures x.i = j
*)

val neg : t -> t
(*@ j = neg i
    ensures j.i = (- i.i) *)

val show : t -> string
```

and for the Ortac config:

```ocaml
open Int31lib.Int31
type sut = t
let init_sut = of_int 42

module Pp = struct
  include Util.Pp

  let pp_t b fmt t = Util.Pp.pp_string b fmt (show t)
end

module Gen = struct
  include QCheck.Gen

  let int = int
  let t = of_int <$> int
end

module Ty = struct
  type _ ty += T : t ty

  let t =
    (T, show)
end
```

But I get a message telling me that `neg` returns a SUT and thus cannot be tested.
```
Error: The generated cmd type is empty.
File "int31.mli", line 9, characters 15-16:
9 | val neg : t -> t
                   ^
Warning: Skipping neg: functions returning a SUT value cannot be tested.
File "int31.mli", line 13, characters 0-22:
13 | val show : t -> string
     ^^^^^^^^^^^^^^^^^^^^^^
Warning: Skipping show: functions without specifications cannot be tested.
```

Is this expected? Can I work around it somehow?

**Comment by nikolaushuber** [comment]
It seems that there is some problem with the version of ortac here. The current main branch has support for testing functions that return SUTs, and the particular error message you are getting is not even part of the `reserr` [module](https://github.com/ocaml-gospel/ortac/blob/0753c72567b83f50ff1d66342c12aafe7dd881b5/plugins/qcheck-stm/src/reserr.ml) anymore.

**Comment by OlivierNicole** [comment]
`ortac --version` is saying `0753c72`. That’s the current `main` :thinking:

**Comment by nikolaushuber** [comment]
We seem to have collaboratively solved it. The trick was to pin both `ortac` and `ortac-qcheck-stm` to the development version 😄

**Comment by OlivierNicole** [comment]
I confirm this seems to work now :)
