### ISSUE TITLE
Internal error (raised exception) caused by x : unit

### ISSUE THREAD

**Issue by naomiiiiiiiii** [ocaml-gospel/ortac#63]
### Example
With file

```
(*example1.mli*)
val test: unit
```
running `ortac example1.mli` produces

```
~ ᐅ ortac example1.mli
ortac: internal error, uncaught exception:
       File "src/core/translate.ml", line 113, characters 4-10: Assertion failed
```

Interestingly, the file 
```
(*example2.mli*)
val test: int
```
does not cause this error.

### Cause

The exception is raised by the function `constant`, which expects the argument ``vd`` to have a singleton list of return values. Upon commenting out the assert on line 113 and re-executing my test, I see that `val test: unit` is processed into a `Tast.val_description` with an empty list of return values.
 From this I conclude that all constants  _should_ have a singleton list of return values. While turning`val test: unit` into a `Tast.val_description`, an error sets the field `vd_ret` to the empty list .
I think that this error occurs on line 877 of ``gospel/src/typing.ml``, inside the function ``process_val``. Here, the variable ``rets``, which becomes the problematic ``vd.vd_ret`` field in ``constant``, is set to the empty list when computing example1. This is because the first clause of the match on `ret` is taken when ``ret`` represents unit (unit is the tuple with arity 0, so ``is_ts_tuple ts`` evaluates to true and `List.init 0...` gives the empty list).  When computing example2, ``ret`` represents int, which is not a tuple, and so the second clause of the match is taken. 

### Solution
There are two paths we could take.

1. I think this can be solved by adding another check on line 879 of ``gospel/src/typing.ml``, something like:
`` | { ty_node = Tyapp (ts, _) } when (is_ts_tuple ts  &&  ts_arity ts <> 0) ->``
to prevent the first clause from applying in the unit case. Example1 can be run successfully with this change.
However, the above change also forces functions with return type unit to enter the second match clause and be given a non-empty `vd_ret` field by ``process_val``. As it stands, functions with return type unit have empty return lists. I am not sure if this is desired behavior. 

3. If you want to preserve functions that return unit having empty return lists, line 879 could read `` { ty_node = Tyapp (ts, _) } when (is_ts_tuple ts  &&  (ts_arity ts <> 0 || args <> []))``. This still allows all functions to enter the first match clause. Example1 can also be run successfully with this change.

**Comment by n-osborne** [comment]
Fixed by [gospel#386](https://github.com/ocaml-gospel/gospel/pull/386)
